# Generated by Django 5.0.1 on 2024-01-23 21:06

import skokho.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='name', max_length=255)),
                ('surname', models.CharField(default='surname', max_length=255)),
                ('business_name', models.CharField(default='business name', max_length=255)),
                ('passport_number', models.CharField(default='EN000000', max_length=20)),
                ('business_number', models.CharField(default='000000000000', max_length=12)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to=skokho.models.passport_upload_to)),
                ('ck_image', models.ImageField(blank=True, null=True, upload_to=skokho.models.ck_upload_to)),
                ('registration_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Opt_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
    ]
