# Generated by Django 5.0.1 on 2024-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skokho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='middle name', max_length=255, null=True),
        ),
    ]
